import CompanyLogo from "./Assets/CompanyLogo.png";

const data = [
  {
    title: "Software Developer Intern",
    companyName: "Tata Consultancy Services",
    comanyLogo: CompanyLogo,
    duration: 3,
    stipendStart: 10000,
    stipendEnd: 15000,
    applicants: 100,
    experience: "Intermediate",
    location: "Remote",
    openings: 10,
    aboutUs:
      "We are a mobile and web development company. We're a professional, individualistic one-stop shop providing strategic brand consulting, experience and customer journey design, mobile app design and development, website and software development, and just about everything else which has to do anything with digital technology. ",
    endsIn: 3,
    skills: [
      "ExpressJS",
      "MongoDB",
      "ReactJS",
      "Redux",
      "ExpressJS",
      "MongoDB",
    ],
    requirements: [
      "Someone who can work in a fast-paced startup environment ",
      "Good understanding of ReactJs, HTML, SCSS (styling is important), Javascript ",
      "Good communication is a must-have for this role",
      "Hardworking & Curious to learn/implement new things is what I prefer personally",
    ],
    responsibilities: [
      "Write clean, manageable code and follow standard coding practices",
      "Write quality code with a clean UI/UX view",
      "Work with the tech & non-tech teams to create a meaningful product for users",
      "Capable to build a feature, testing, and deploying a feature on the production server",
    ],
  },
  {
    title: "Motion Graphics Designer",
    companyName: "Xapo Visuals",
    comanyLogo: CompanyLogo,
    duration: 3,
    stipendStart: 10000,
    stipendEnd: 15000,
    applicants: 100,
    experience: "Intermediate",
    location: "Remote",
    openings: 10,
    aboutUs:
      "We are a mobile and web development company. We're a professional, individualistic one-stop shop providing strategic brand consulting, experience and customer journey design, mobile app design and development, website and software development, and just about everything else which has to do anything with digital technology. ",
    endsIn: 3,
    skills: [
      "ExpressJS",
      "MongoDB",
      "ReactJS",
      "Redux",
      "ExpressJS",
      "MongoDB",
    ],
    requirements: [
      "Someone who can work in a fast-paced startup environment ",
      "Good understanding of ReactJs, HTML, SCSS (styling is important), Javascript ",
      "Good communication is a must-have for this role",
      "Hardworking & Curious to learn/implement new things is what I prefer personally",
    ],
    responsibilities: [
      "Write clean, manageable code and follow standard coding practices",
      "Write quality code with a clean UI/UX view",
      "Work with the tech & non-tech teams to create a meaningful product for users",
      "Capable to build a feature, testing, and deploying a feature on the production server",
    ],
  },
  {
    title: "Software Developer Intern",
    companyName: "Tata Consultancy Services",
    comanyLogo: CompanyLogo,
    duration: 3,
    stipendStart: 10000,
    stipendEnd: 15000,
    applicants: 100,
    experience: "Intermediate",
    location: "Remote",
    openings: 10,
    aboutUs:
      "We are a mobile and web development company. We're a professional, individualistic one-stop shop providing strategic brand consulting, experience and customer journey design, mobile app design and development, website and software development, and just about everything else which has to do anything with digital technology. ",
    endsIn: 3,
    skills: [
      "ExpressJS",
      "MongoDB",
      "ReactJS",
      "Redux",
      "ExpressJS",
      "MongoDB",
    ],
    requirements: [
      "Someone who can work in a fast-paced startup environment ",
      "Good understanding of ReactJs, HTML, SCSS (styling is important), Javascript ",
      "Good communication is a must-have for this role",
      "Hardworking & Curious to learn/implement new things is what I prefer personally",
    ],
    responsibilities: [
      "Write clean, manageable code and follow standard coding practices",
      "Write quality code with a clean UI/UX view",
      "Work with the tech & non-tech teams to create a meaningful product for users",
      "Capable to build a feature, testing, and deploying a feature on the production server",
    ],
  },
  {
    title: "Software Developer Intern",
    companyName: "Tata Consultancy Services",
    comanyLogo: CompanyLogo,
    duration: 3,
    stipendStart: 10000,
    stipendEnd: 15000,
    applicants: 100,
    experience: "Intermediate",
    location: "Remote",
    openings: 10,
    aboutUs:
      "We are a mobile and web development company. We're a professional, individualistic one-stop shop providing strategic brand consulting, experience and customer journey design, mobile app design and development, website and software development, and just about everything else which has to do anything with digital technology. ",
    endsIn: 3,
    skills: [
      "ExpressJS",
      "MongoDB",
      "ReactJS",
      "Redux",
      "ExpressJS",
      "MongoDB",
    ],
    requirements: [
      "Someone who can work in a fast-paced startup environment ",
      "Good understanding of ReactJs, HTML, SCSS (styling is important), Javascript ",
      "Good communication is a must-have for this role",
      "Hardworking & Curious to learn/implement new things is what I prefer personally",
    ],
    responsibilities: [
      "Write clean, manageable code and follow standard coding practices",
      "Write quality code with a clean UI/UX view",
      "Work with the tech & non-tech teams to create a meaningful product for users",
      "Capable to build a feature, testing, and deploying a feature on the production server",
    ],
  },
  {
    title: "Software Developer Intern",
    companyName: "Tata Consultancy Services",
    comanyLogo: CompanyLogo,
    duration: 3,
    stipendStart: 10000,
    stipendEnd: 15000,
    applicants: 100,
    experience: "Intermediate",
    location: "Remote",
    openings: 10,
    aboutUs:
      "We are a mobile and web development company. We're a professional, individualistic one-stop shop providing strategic brand consulting, experience and customer journey design, mobile app design and development, website and software development, and just about everything else which has to do anything with digital technology. ",
    endsIn: 3,
    skills: [
      "ExpressJS",
      "MongoDB",
      "ReactJS",
      "Redux",
      "ExpressJS",
      "MongoDB",
    ],
    requirements: [
      "Someone who can work in a fast-paced startup environment ",
      "Good understanding of ReactJs, HTML, SCSS (styling is important), Javascript ",
      "Good communication is a must-have for this role",
      "Hardworking & Curious to learn/implement new things is what I prefer personally",
    ],
    responsibilities: [
      "Write clean, manageable code and follow standard coding practices",
      "Write quality code with a clean UI/UX view",
      "Work with the tech & non-tech teams to create a meaningful product for users",
      "Capable to build a feature, testing, and deploying a feature on the production server",
    ],
  },
];
export default data;
